name: CI

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Python dependencies
        run: |
          pip3 install --user python-dateutil linkchecker

      - name: Download and install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.21.0/zola-v0.21.0-x86_64-unknown-linux-gnu.tar.gz
          tar xvf zola-v0.21.0-x86_64-unknown-linux-gnu.tar.gz

      - name: Put pip binary directory into path
        run: echo "~/.local/bin" >> $GITHUB_PATH

      - name: Build book
        run: ./zola build

      - name: Check links
        run: linkchecker public/

      - name: Deploy book
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
          cname: blog.rust-embedded.org
